# Category definitions and seed product data for Apex Trading & Supply Co.

CATEGORIES = [
    {
        "slug": "food-ingredient",
        "name": "Food & Ingredient Supply",
        "tagline": "Bulk grains, oils, spices & packaged ingredients",
        "description": "Premium-grade food ingredients and raw materials sourced from trusted global producers. Reliable bulk supply for manufacturers, distributors and foodservice operators.",
        "image": "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=1200&q=80",
    },
    {
        "slug": "kitchen-supply",
        "name": "Kitchen Supply",
        "tagline": "Commercial kitchen equipment & stainless steel ware",
        "description": "Durable, professional-grade kitchen equipment and smallware engineered for high-volume commercial kitchens, restaurants and hospitality businesses.",
        "image": "https://images.unsplash.com/photo-1589109807644-924edf14ee09?w=1200&q=80",
    },
    {
        "slug": "construction",
        "name": "Construction",
        "tagline": "Building materials, steel, cement & site tools",
        "description": "A complete range of construction materials and supplies \u2014 from structural steel and cement to finishing materials \u2014 delivered on schedule for projects of any scale.",
        "image": "https://images.unsplash.com/photo-1761479867761-7a8b11f54449?w=1200&q=80",
    },
    {
        "slug": "trading-wholesale",
        "name": "Trading Company (Wholesale)",
        "tagline": "Wholesale distribution & global sourcing",
        "description": "End-to-end wholesale trading and sourcing solutions. We connect buyers and suppliers worldwide with competitive pricing, logistics and dependable fulfilment.",
        "image": "https://images.unsplash.com/photo-1672552226380-486fe900b322?w=1200&q=80",
    },
]

CATEGORY_SLUGS = [c["slug"] for c in CATEGORIES]

SEED_PRODUCTS = [
    # ---------------- Food & Ingredient Supply ----------------
    {
        "title": "Premium Long-Grain Basmati Rice",
        "category": "food-ingredient",
        "sku": "FD-RICE-001",
        "short_description": "Aged, aromatic long-grain basmati rice supplied in bulk 25kg sacks.",
        "description": "Hand-selected, naturally aged basmati rice with extra-long grains and a distinctive aroma. Ideal for foodservice, retail repackaging and export. Consistent quality with full traceability and food-safety certification.",
        "specs": [
            {"label": "Grain Type", "value": "Long-grain, aged 12 months"},
            {"label": "Packaging", "value": "25 kg PP woven sack"},
            {"label": "Moisture", "value": "< 12%"},
            {"label": "MOQ", "value": "5 metric tons"},
            {"label": "Certification", "value": "ISO 22000, HACCP"},
        ],
        "stock_status": "in_stock",
        "featured": True,
        "images": ["https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=900&q=80"],
    },
    {
        "title": "Bulk Whole & Ground Spices",
        "category": "food-ingredient",
        "sku": "FD-SPICE-002",
        "short_description": "Wide range of whole and ground spices in food-grade bulk packaging.",
        "description": "Premium whole and ground spices including turmeric, cumin, coriander, paprika and chili. Lab-tested for purity and color value, packed in moisture-barrier bulk bags for extended shelf life.",
        "specs": [
            {"label": "Varieties", "value": "20+ spice types"},
            {"label": "Packaging", "value": "10 / 25 kg food-grade bags"},
            {"label": "Purity", "value": "99.5% min"},
            {"label": "MOQ", "value": "500 kg per SKU"},
            {"label": "Shelf Life", "value": "24 months"},
        ],
        "stock_status": "in_stock",
        "featured": False,
        "images": ["https://images.unsplash.com/photo-1606914501449-5a96b6ce24ca?w=900&q=80"],
    },
    {
        "title": "Refined Sunflower Cooking Oil",
        "category": "food-ingredient",
        "sku": "FD-OIL-003",
        "short_description": "Refined, deodorized sunflower oil in bulk flexitanks and drums.",
        "description": "High-quality refined sunflower oil suitable for frying, cooking and food manufacturing. Available in IBC totes, drums and flexitanks for large-volume buyers.",
        "specs": [
            {"label": "Type", "value": "Refined, winterized"},
            {"label": "Packaging", "value": "Drums / IBC / Flexitank"},
            {"label": "Free Fatty Acid", "value": "< 0.1%"},
            {"label": "MOQ", "value": "1 FCL (20 MT)"},
            {"label": "Origin", "value": "Multiple sources"},
        ],
        "stock_status": "made_to_order",
        "featured": True,
        "images": ["https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=900&q=80"],
    },
    # ---------------- Kitchen Supply ----------------
    {
        "title": "Commercial Stainless Steel Work Table",
        "category": "kitchen-supply",
        "sku": "KS-TBL-101",
        "short_description": "Heavy-duty 304 stainless steel prep table for commercial kitchens.",
        "description": "Robust 304-grade stainless steel work table with adjustable undershelf and leveling feet. Welded construction withstands the demands of busy commercial kitchens and complies with food-safety standards.",
        "specs": [
            {"label": "Material", "value": "304 Stainless Steel"},
            {"label": "Dimensions", "value": "1800 x 700 x 850 mm"},
            {"label": "Load Capacity", "value": "200 kg"},
            {"label": "Gauge", "value": "1.2 mm top"},
            {"label": "Warranty", "value": "2 years"},
        ],
        "stock_status": "in_stock",
        "featured": True,
        "images": ["https://images.unsplash.com/photo-1708915965975-2a950db0e215?w=900&q=80"],
    },
    {
        "title": "Professional Cookware & Utensil Set",
        "category": "kitchen-supply",
        "sku": "KS-UTL-102",
        "short_description": "Complete stainless steel cookware and utensil set for restaurants.",
        "description": "Durable commercial cookware and utensil set including pots, pans, ladles and turners. Ergonomic riveted handles and induction-ready bases for professional foodservice environments.",
        "specs": [
            {"label": "Pieces", "value": "32-piece set"},
            {"label": "Material", "value": "18/10 Stainless Steel"},
            {"label": "Compatibility", "value": "Gas / Induction / Electric"},
            {"label": "MOQ", "value": "20 sets"},
            {"label": "Packaging", "value": "Export carton"},
        ],
        "stock_status": "in_stock",
        "featured": False,
        "images": ["https://images.pexels.com/photos/4947388/pexels-photo-4947388.jpeg?w=900"],
    },
    {
        "title": "Industrial Kitchen Equipment Package",
        "category": "kitchen-supply",
        "sku": "KS-PKG-103",
        "short_description": "Turnkey commercial kitchen equipment package for new setups.",
        "description": "A configurable package of commercial cooking, refrigeration and prep equipment for restaurants, hotels and canteens. Custom layouts and installation support available.",
        "specs": [
            {"label": "Includes", "value": "Ranges, fryers, prep, storage"},
            {"label": "Material", "value": "Stainless Steel"},
            {"label": "Customization", "value": "Layout to spec"},
            {"label": "Lead Time", "value": "4-6 weeks"},
            {"label": "Support", "value": "Installation & training"},
        ],
        "stock_status": "made_to_order",
        "featured": False,
        "images": ["https://images.pexels.com/photos/34276646/pexels-photo-34276646.jpeg?w=900"],
    },
    # ---------------- Construction ----------------
    {
        "title": "Deformed Steel Reinforcement Bar (Rebar)",
        "category": "construction",
        "sku": "CN-REB-201",
        "short_description": "High-tensile deformed rebar for structural concrete works.",
        "description": "Grade-rated deformed steel reinforcement bars manufactured to international standards. Excellent bonding with concrete and consistent mechanical properties for structural reliability.",
        "specs": [
            {"label": "Grade", "value": "B500B / Grade 60"},
            {"label": "Diameter", "value": "8 - 32 mm"},
            {"label": "Length", "value": "12 m standard"},
            {"label": "Standard", "value": "ASTM A615 / BS4449"},
            {"label": "MOQ", "value": "25 metric tons"},
        ],
        "stock_status": "in_stock",
        "featured": True,
        "images": ["https://images.unsplash.com/photo-1761479867761-7a8b11f54449?w=900&q=80"],
    },
    {
        "title": "Ordinary Portland Cement (OPC 53 Grade)",
        "category": "construction",
        "sku": "CN-CEM-202",
        "short_description": "High-strength OPC 53 grade cement in bulk and bagged supply.",
        "description": "Premium Ordinary Portland Cement offering high early and ultimate strength for structural concrete, precast and infrastructure projects. Available bagged or in bulk.",
        "specs": [
            {"label": "Grade", "value": "OPC 53"},
            {"label": "Packaging", "value": "50 kg bag / bulk"},
            {"label": "Compressive Strength", "value": "53 MPa @ 28 days"},
            {"label": "Standard", "value": "EN 197-1 / IS 12269"},
            {"label": "MOQ", "value": "1 FCL"},
        ],
        "stock_status": "in_stock",
        "featured": False,
        "images": ["https://images.pexels.com/photos/36003985/pexels-photo-36003985.jpeg?w=900"],
    },
    {
        "title": "Construction Site Material Pallets",
        "category": "construction",
        "sku": "CN-PAL-203",
        "short_description": "Palletized mixed building materials for project delivery.",
        "description": "Consolidated palletized supply of bricks, blocks, timber and finishing materials for streamlined site logistics. Scheduled deliveries to keep your project on track.",
        "specs": [
            {"label": "Contents", "value": "Configurable per project"},
            {"label": "Handling", "value": "Forklift / crane ready"},
            {"label": "Delivery", "value": "Scheduled to site"},
            {"label": "Coverage", "value": "Regional & export"},
            {"label": "Lead Time", "value": "3-5 days"},
        ],
        "stock_status": "in_stock",
        "featured": False,
        "images": ["https://images.pexels.com/photos/36463675/pexels-photo-36463675.jpeg?w=900"],
    },
    # ---------------- Trading / Wholesale ----------------
    {
        "title": "Wholesale Pallet Consolidation",
        "category": "trading-wholesale",
        "sku": "TR-PAL-301",
        "short_description": "Mixed-SKU pallet and container consolidation for wholesalers.",
        "description": "Flexible wholesale consolidation service combining multiple SKUs into optimized pallets and containers. Reduce freight cost and simplify import for distributors and retailers.",
        "specs": [
            {"label": "Service", "value": "LCL / FCL consolidation"},
            {"label": "Sourcing", "value": "Global supplier network"},
            {"label": "Incoterms", "value": "FOB / CIF / DDP"},
            {"label": "MOQ", "value": "Negotiable"},
            {"label": "Lead Time", "value": "2-4 weeks"},
        ],
        "stock_status": "in_stock",
        "featured": True,
        "images": ["https://images.unsplash.com/photo-1672552226380-486fe900b322?w=900&q=80"],
    },
    {
        "title": "Wholesale Packaged Goods Distribution",
        "category": "trading-wholesale",
        "sku": "TR-PKG-302",
        "short_description": "Bulk packaged consumer & industrial goods for resale.",
        "description": "Reliable wholesale distribution of packaged consumer and industrial goods. Competitive pricing, dependable stock availability and full logistics support for resellers.",
        "specs": [
            {"label": "Categories", "value": "FMCG / Industrial"},
            {"label": "Packaging", "value": "Cartons / Pallets"},
            {"label": "Pricing", "value": "Tiered volume pricing"},
            {"label": "MOQ", "value": "1 pallet"},
            {"label": "Logistics", "value": "Door-to-door available"},
        ],
        "stock_status": "in_stock",
        "featured": False,
        "images": ["https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=900&q=80"],
    },
]
