# Curated catalog + categories for True Manufacturing premium kitchen store

SHOP_CATEGORIES = [
    {
        "slug": "cutlery",
        "name": "Cutlery & Knives",
        "tagline": "Forged precision for the professional line",
        "image": "https://images.unsplash.com/photo-1614362705324-8da11fd16754?w=1000&q=80",
    },
    {
        "slug": "cookware",
        "name": "Cookware",
        "tagline": "Heat-true pans built to last a career",
        "image": "https://images.unsplash.com/photo-1604414499020-f9ac575bc5ec?w=1000&q=80",
    },
    {
        "slug": "prep",
        "name": "Prep Tools",
        "tagline": "The essentials behind every great dish",
        "image": "https://images.unsplash.com/photo-1666013942797-9daa4b8b3b4f?w=1000&q=80",
    },
    {
        "slug": "commercial",
        "name": "Commercial Equipment",
        "tagline": "Workhorse equipment for the production kitchen",
        "image": "https://images.unsplash.com/photo-1601599967100-f16100982063?w=1000&q=80",
    },
    {
        "slug": "utensils",
        "name": "Utensils & Smallwares",
        "tagline": "Refined tools for everyday service",
        "image": "https://images.unsplash.com/photo-1592771584685-c3c2edcd5c31?w=1000&q=80",
    },
]

SHOP_CATEGORY_SLUGS = [c["slug"] for c in SHOP_CATEGORIES]

SHOP_PRODUCTS = [
    # ---------------- Cutlery & Knives ----------------
    {
        "name": "Forged 8\" Chef's Knife",
        "category": "cutlery", "sku": "TM-KN-801", "price": 189.0,
        "short_description": "A fully forged high-carbon steel chef's knife balanced for all-day service.",
        "description": "The cornerstone of any professional kit. Forged from a single billet of high-carbon stainless steel, the blade holds a razor edge through long prep shifts and resists corrosion in demanding kitchens. A full tang and bolster deliver the balance and control chefs rely on, while the ergonomic handle stays secure even with wet hands.",
        "features": ["High-carbon stainless steel blade", "Full tang for balance", "Hand-honed 15\u00b0 edge", "Riveted ergonomic handle"],
        "image": "https://images.unsplash.com/photo-1614362705324-8da11fd16754?w=800&q=80",
        "in_stock": True, "featured": True,
    },
    {
        "name": "7\" Santoku Knife",
        "category": "cutlery", "sku": "TM-KN-702", "price": 165.0,
        "short_description": "A nimble, granton-edged santoku for precision slicing and clean release.",
        "description": "Engineered for speed and control, this santoku features a thin, hardened blade with hollow-ground granton dimples that keep food from sticking. Ideal for fine vegetable work, fish, and boneless proteins, it brings effortless agility to detailed prep.",
        "features": ["Granton hollow-edge", "Hardened to 58 HRC", "Thin precision blade", "Slip-resistant grip"],
        "image": "https://images.unsplash.com/photo-1688398349642-bffda773e687?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "3.5\" Paring Knife",
        "category": "cutlery", "sku": "TM-KN-353", "price": 79.0,
        "short_description": "A sharp, agile paring knife for detail work and intricate cuts.",
        "description": "Small in the hand, indispensable on the board. This paring knife pairs a precision-ground tip with a comfortable handle for peeling, trimming, and delicate garnish work where a chef's knife is too large.",
        "features": ["Precision-ground tip", "High-carbon steel", "Lightweight control", "Dishwasher-safe handle"],
        "image": "https://images.unsplash.com/photo-1596299085622-4f96269e5bc7?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "Professional Honing Steel",
        "category": "cutlery", "sku": "TM-KN-010", "price": 59.0,
        "short_description": "Realign your edge between sharpenings with a 10\" fine honing rod.",
        "description": "A daily-use honing steel that keeps blades true between full sharpenings. The fine-cut rod gently realigns the cutting edge, extending sharpness and prolonging the life of your cutlery investment.",
        "features": ["10\" fine-cut rod", "Hardened steel core", "Guard for safe honing", "Hanging loop"],
        "image": "https://images.unsplash.com/photo-1623947851502-49082c0d8ab8?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    # ---------------- Prep Tools ----------------
    {
        "name": "End-Grain Maple Cutting Board",
        "category": "prep", "sku": "TM-PR-201", "price": 145.0,
        "short_description": "A thick end-grain maple board that's gentle on edges and built to endure.",
        "description": "Crafted from kiln-dried hard maple in a true end-grain construction, this board self-heals against knife marks and protects your blades. Generous thickness provides a stable, quiet work surface for high-volume prep.",
        "features": ["End-grain hard maple", "Edge-friendly surface", "Juice groove", "Food-safe mineral finish"],
        "image": "https://images.unsplash.com/photo-1666013942797-9daa4b8b3b4f?w=800&q=80",
        "in_stock": True, "featured": True,
    },
    {
        "name": "Stainless Mixing Bowl Set (5-Pc)",
        "category": "prep", "sku": "TM-PR-205", "price": 89.0,
        "short_description": "Nesting stainless bowls for mixing, marinating, and mise en place.",
        "description": "A five-piece set of polished 18/8 stainless bowls that nest for compact storage. Lightweight yet durable, they resist staining and odors and move effortlessly from prep to cooler.",
        "features": ["18/8 stainless steel", "Nesting design", "Rolled rims", "Stain & odor resistant"],
        "image": "https://images.unsplash.com/photo-1593143303977-01da2fd61984?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "Professional Mandoline Slicer",
        "category": "prep", "sku": "TM-PR-210", "price": 119.0,
        "short_description": "Consistent, precise slices and juliennes with adjustable thickness.",
        "description": "Achieve uniform cuts in seconds. This mandoline features a razor-sharp stainless blade with adjustable thickness settings and interchangeable julienne inserts, complete with a hand guard for safe, repeatable results.",
        "features": ["Adjustable thickness", "Stainless steel blades", "Julienne inserts", "Safety hand guard"],
        "image": "https://images.unsplash.com/photo-1759987384448-16ac3dbc27b1?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "Digital Kitchen Scale",
        "category": "prep", "sku": "TM-PR-215", "price": 65.0,
        "short_description": "Gram-accurate weighing for consistent recipes and portion control.",
        "description": "Precision is the difference between good and great. This tare-enabled digital scale weighs to the gram across a wide capacity, with a sealed stainless platform that wipes clean between tasks.",
        "features": ["1g resolution", "11 lb / 5 kg capacity", "Tare function", "Sealed stainless platform"],
        "image": "https://images.unsplash.com/photo-1612012060851-20f943c02d3d?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    # ---------------- Cookware ----------------
    {
        "name": "Tri-Ply 12\" Saut\u00e9 Pan",
        "category": "cookware", "sku": "TM-CW-312", "price": 199.0,
        "short_description": "A tri-ply stainless saut\u00e9 pan with an aluminum core for even heat.",
        "description": "Bonded tri-ply construction wraps a responsive aluminum core in durable stainless steel for fast, even heating with no hot spots. Oven-safe and induction-ready, this saut\u00e9 pan delivers professional results from sear to sauce.",
        "features": ["Tri-ply aluminum core", "Induction-ready", "Oven-safe to 500\u00b0F", "Riveted stay-cool handle"],
        "image": "https://images.unsplash.com/photo-1604414499020-f9ac575bc5ec?w=800&q=80",
        "in_stock": True, "featured": True,
    },
    {
        "name": "Carbon Steel 10\" Skillet",
        "category": "cookware", "sku": "TM-CW-310", "price": 95.0,
        "short_description": "A pre-seasoned carbon steel skillet that builds a natural nonstick patina.",
        "description": "The professional alternative to cast iron and nonstick. Lightweight carbon steel heats quickly and develops a natural, slick patina with use. Ideal for high-heat searing, eggs, and finishing in the oven.",
        "features": ["Pre-seasoned carbon steel", "High-heat searing", "Naturally nonstick patina", "Oven & grill safe"],
        "image": "https://images.unsplash.com/photo-1698939586566-8c093b721cb7?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "12-Quart Stainless Stockpot",
        "category": "cookware", "sku": "TM-CW-412", "price": 175.0,
        "short_description": "A heavy-gauge stockpot with an encapsulated base for stocks and batch cooking.",
        "description": "Built for volume, this 12-quart stockpot features heavy-gauge stainless walls and an encapsulated aluminum base for steady, even simmering. Riveted handles and a vented lid make large-batch stocks, sauces, and pasta effortless.",
        "features": ["Heavy-gauge stainless", "Encapsulated aluminum base", "Riveted handles", "Vented lid"],
        "image": "https://images.unsplash.com/photo-1693038603562-bb6191269ecc?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "3-Quart Saucepan",
        "category": "cookware", "sku": "TM-CW-303", "price": 129.0,
        "short_description": "A versatile tri-ply saucepan for sauces, grains, and reductions.",
        "description": "An everyday workhorse for the line. Tri-ply construction delivers precise, even heat for delicate sauces and reductions, while the tight-fitting lid locks in moisture for grains and braises.",
        "features": ["Tri-ply construction", "Tight-fitting lid", "Induction-ready", "Pour-friendly rim"],
        "image": "https://images.pexels.com/photos/12156176/pexels-photo-12156176.jpeg?auto=compress&cs=tinysrgb&w=800",
        "in_stock": True, "featured": False,
    },
    {
        "name": "6-Quart Cast Iron Dutch Oven",
        "category": "cookware", "sku": "TM-CW-606", "price": 219.0,
        "short_description": "An enameled cast iron Dutch oven for braising, roasting, and baking.",
        "description": "Superior heat retention for slow braises, crusty breads, and deep stews. Enameled cast iron resists chips and staining, transitions seamlessly from stovetop to oven, and develops rich flavor with every use.",
        "features": ["Enameled cast iron", "Excellent heat retention", "Oven-safe to 500\u00b0F", "Self-basting lid"],
        "image": "https://images.unsplash.com/photo-1766746842414-e7a999ca83ce?w=800&q=80",
        "in_stock": True, "featured": True,
    },
    # ---------------- Commercial Equipment ----------------
    {
        "name": "Commercial Reach-In Refrigerator",
        "category": "commercial", "sku": "TM-CE-100", "price": 3499.0,
        "short_description": "A stainless reach-in refrigerator engineered for the coldest, most consistent holding temperatures.",
        "description": "True to our refrigeration heritage, this reach-in holds precise, stable temperatures even during peak service. A high-efficiency hydrocarbon system, thick foamed-in-place insulation, and self-closing doors protect product quality while keeping energy costs low.",
        "features": ["Hydrocarbon refrigeration system", "Stainless steel construction", "Self-closing doors", "Energy Star rated"],
        "image": "https://images.unsplash.com/photo-1601599967100-f16100982063?w=800&q=80",
        "in_stock": True, "featured": True,
    },
    {
        "name": "Professional Induction Range",
        "category": "commercial", "sku": "TM-CE-210", "price": 2899.0,
        "short_description": "A multi-zone induction range delivering instant, precise, energy-efficient heat.",
        "description": "Restaurant-grade induction cooking with instant response and pinpoint control. Multiple independent zones heat cookware directly for faster results, a cooler kitchen, and dramatically lower energy use than gas.",
        "features": ["Multi-zone induction", "Instant heat response", "Stainless body", "Energy-efficient cooking"],
        "image": "https://images.unsplash.com/photo-1723902500132-7de6112d5627?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "Countertop Induction Cooktop",
        "category": "commercial", "sku": "TM-CE-215", "price": 349.0,
        "short_description": "A portable induction cooktop for stations, catering, and front-of-house cooking.",
        "description": "Precise, portable power wherever service demands it. This countertop induction unit offers fine temperature control and rapid heating in a compact, easy-to-clean footprint \u2014 ideal for action stations and catering.",
        "features": ["Precise temperature control", "Rapid heating", "Compact footprint", "Touch controls"],
        "image": "https://images.unsplash.com/photo-1722764386949-68927cb04eb5?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "Commercial Stand Mixer",
        "category": "commercial", "sku": "TM-CE-300", "price": 749.0,
        "short_description": "A planetary stand mixer built for doughs, batters, and high-volume mixing.",
        "description": "Power through dense doughs and large batches with a heavy-duty planetary mixing action. An all-metal drivetrain, generous bowl capacity, and multiple speeds make this mixer a dependable centerpiece of any bakery or production kitchen.",
        "features": ["Planetary mixing action", "All-metal drivetrain", "Large-capacity bowl", "Multiple speed settings"],
        "image": "https://images.unsplash.com/photo-1547091267-6b2be403a763?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    # ---------------- Utensils & Smallwares ----------------
    {
        "name": "Stainless Steel Tongs (Set of 2)",
        "category": "utensils", "sku": "TM-US-402", "price": 39.0,
        "short_description": "Spring-loaded stainless tongs with scalloped tips for a sure grip.",
        "description": "An extension of the chef's hand. These spring-loaded tongs feature scalloped, welded tips for a secure grip on everything from delicate greens to seared proteins, with a locking ring for tidy storage.",
        "features": ["Welded scalloped tips", "Spring-loaded action", "9\" & 12\" pair", "Locking ring"],
        "image": "https://images.unsplash.com/photo-1592771584685-c3c2edcd5c31?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "Silicone Spatula Set",
        "category": "utensils", "sku": "TM-US-405", "price": 45.0,
        "short_description": "Heat-resistant silicone spatulas with seamless, hygienic construction.",
        "description": "Built for hot pans and constant use, these seamless silicone spatulas resist heat to 600\u00b0F and won't harbor bacteria. Flexible heads scrape clean while protecting nonstick and finished cookware.",
        "features": ["Heat-safe to 600\u00b0F", "Seamless hygienic build", "Flexible scraping head", "Dishwasher safe"],
        "image": "https://images.unsplash.com/photo-1675264123540-e74419f2ac73?w=800&q=80",
        "in_stock": True, "featured": False,
    },
    {
        "name": "Fine Mesh Strainer",
        "category": "utensils", "sku": "TM-US-410", "price": 49.0,
        "short_description": "A double-mesh strainer for silky sauces, stocks, and sifting.",
        "description": "Refine every plate. The double-layer fine mesh removes the smallest solids for glass-smooth sauces and clear stocks, with a reinforced rim and hook handle that rests securely over pots and bowls.",
        "features": ["Double-layer fine mesh", "Reinforced rim", "Balance hook", "Stainless construction"],
        "image": "https://images.unsplash.com/photo-1585505642358-2cd65f5c39d4?w=800&q=80",
        "in_stock": True, "featured": False,
    },
]
